controller_list:
  - name: fake_robot_arm_controller
    joints:
      - base-fil_j
      - fil-sel_j
      - sel-thl_j
      - thl-fol_j
      - fol-ffl_j
      - ffl-sil_j
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: home