<?xml version="1.0"?>
<robot name="desktop_robot" xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- create here macro params -->
	<xacro:property name="base_r" value="0.5" />	<!-- base radius -->
	<xacro:property name="base_z" value="0.1" />	<!-- base height -->

	<xacro:property name="fil_x" value="0.7" />	<!-- first link x -->
	<xacro:property name="fil_y" value="0.7" />	<!-- first link y -->
	<xacro:property name="fil_z" value="0.2" />	<!-- first link z -->

	<xacro:property name="sel_x" value="0.1" />	<!-- second link x -->
	<xacro:property name="sel_y" value="0.2" />	<!-- second link y -->
	<xacro:property name="sel_z" value="1" />	<!-- second link z -->

	<xacro:property name="thl_x" value="0.1" />	<!-- third link x -->
	<xacro:property name="thl_y" value="0.2" />	<!-- third link y -->
	<xacro:property name="thl_z" value="1" />	<!-- third link z -->

	<xacro:property name="fol_x" value="0.1" />	<!-- fourth link x -->
	<xacro:property name="fol_y" value="0.3" />	<!-- fourth link y -->
	<xacro:property name="fol_z" value="0.1" />	<!-- fourth link z -->

	<xacro:property name="ffl_x" value="0.1" />	<!-- fifth link x -->
	<xacro:property name="ffl_y" value="0.2" />	<!-- fifth link y -->
	<xacro:property name="ffl_z" value="0.05" />	<!-- fifth link z -->

	<xacro:property name="sil_x" value="0.1" />	<!-- sixth link x -->
	<xacro:property name="sil_y" value="0.1" />	<!-- sixth link y -->
	<xacro:property name="sil_z" value="0.3" />	<!-- sixth link z -->

	<!-- create here materials/colours -->
	<material name="blue">
	    <color rgba="0 0 1 1"/>
	 </material>
	 <material name="red">
	    <color rgba="1 0 0 1"/>
	 </material>
	 <material name="green">
	    <color rgba="0 1 0 1"/>
	 </material>
	 <material name="white">
	    <color rgba="1 1 1 1"/>
	 </material>
	 <material name="yellow">
	    <color rgba="1 1 0 1"/>
	 </material>
	 <material name="magenta">
	    <color rgba="1 0 1 1"/>
	 </material>
	 <material name="cyan">
	    <color rgba="0 1 1 1"/>
	 </material>
	<!-- create here links -->
	 <link name="base_link">
	    <!-- used for visual appearance -->
	    <visual>
	      <geometry>
		<!-- list with all the different options -->
		<cylinder length="${base_z}" radius="${base_r}"/>
	      </geometry>
	      <material name="red"/>
	      <origin rpy="0 0 0" xyz="0 0 ${0.5*base_z}"/>
	    </visual>
	  </link>

	 <link name="first_link">
	    <!-- used for visual appearance -->
	    <visual>
	      <geometry>
		<!-- list with all the different options -->
		<box size="${fil_x} ${fil_y} ${fil_z}"/>
	      </geometry>
	      <material name="blue"/>
	      <origin rpy="0 0 0" xyz="0 0 ${fil_z/2}"/>
	    </visual>
	  </link>

	 <link name="second_link">
	    <!-- used for visual appearance -->
	    <visual>
	      <geometry>
		<!-- list with all the different options -->
		<box size="${sel_x} ${sel_y} ${sel_z}"/>
	      </geometry>
	      <material name="green"/>
	      <origin rpy="0 0 0" xyz="0 0 ${sel_z/2}"/>
	    </visual>
	 </link>
	 
  	 <link name="third_link">
	    <!-- used for visual appearance -->
	    <visual>
	      <geometry>
		<!-- list with all the different options -->
		<box size="${thl_x} ${thl_y} ${thl_z}"/>
	      </geometry>
	      <material name="yellow"/>
	      <origin rpy="0 0 0" xyz="0 0 ${thl_z/2}"/>
    </visual>
  </link>
  <link name="fourth_link">
	    <!-- used for visual appearance -->
	    <visual>
	      <geometry>
		<!-- list with all the different options -->
		<box size="${fol_x} ${fol_y} ${fol_z}"/>
	      </geometry>
	      <material name="magenta"/>
	      <origin rpy="0 0 0" xyz="0 0 ${fol_z/2}"/>
    </visual>
  </link>
  <link name="fifth_link">
	    <!-- used for visual appearance -->
	    <visual>
	      <geometry>
		<!-- list with all the different options -->
		<box size="${ffl_x} ${ffl_y} ${ffl_z}"/>
	      </geometry>
	      <material name="cyan"/>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
  </link>
  <link name="sixth_link">
	    <!-- used for visual appearance -->
	    <visual>
	      <geometry>
		<!-- list with all the different options -->
		<box size="${sil_x} ${sil_y} ${sil_z}"/>
	      </geometry>
	      <material name="white"/>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
  </link>

	<!-- create here continuous joints -->
	  <joint name="base-fil_j" type="continuous">	<!-- create joint between base and first link-->
	    <axis rpy="0 0 0" xyz="0 0 1"/>
	    <parent link="base_link"/>
	    <child link="first_link"/>
	    <origin rpy="0 0 0" xyz="0 0 ${base_z}"/>
	  </joint>

	  <joint name="fil-sel_j" type="continuous">	<!-- create joint between first and second link-->
	    <axis rpy="0 0 0" xyz="0 1 0"/>
	    <parent link="first_link"/>
	    <child link="second_link"/>
	    <origin rpy="0 0 0" xyz="${fil_x/2} 0 ${fil_z}"/>
	  </joint>

	  <joint name="sel-thl_j" type="continuous">	<!-- create joint between second and third link-->
	    <axis rpy="0 0 0" xyz="0 1 0"/>
	    <parent link="second_link"/>
	    <child link="third_link"/>
	    <origin rpy="0 0 0" xyz="0 ${sel_y} ${sel_z}"/>
	  </joint>

	  <joint name="thl-fol_j" type="continuous">	<!-- create joint between third and fourth link-->
	    <axis rpy="0 0 0" xyz="0 0 1"/>
	    <parent link="third_link"/>
	    <child link="fourth_link"/>
	    <origin rpy="0 0 0" xyz="${thl_x/2} 0 ${thl_z}"/>
	  </joint>

	  <joint name="fol-ffl_j" type="continuous">	<!-- create joint between fourth and fifth link-->
		    <axis rpy="0 0 0" xyz="0 1 0"/>
		    <parent link="fourth_link"/>
		    <child link="fifth_link"/>
		    <origin rpy="0 0 0" xyz="${fol_x/2} 0 ${fol_z/2}"/>
	  </joint>
	  <joint name="ffl-sil_j" type="continuous">	<!-- create joint between fifth and sixth link-->
		    <axis rpy="0 0 0" xyz="0 0 1"/>
		    <parent link="fifth_link"/>
		    <child link="sixth_link"/>
		    <origin rpy="0 0 0" xyz="0 0 ${sil_z/2}"/>
	  </joint>
	<!-- create here revolute joints -->


	<!-- create here prismatic joints -->
</robot>
